services:
  jaeger:
    image: jaegertracing/all-in-one:1.6.0
    container_name: jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5778:5778" # configs
      - "16686:16686" # frontend
      - "9411:9411" # Zipkin endpoint
